apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-demo
  namespace: default
spec:
  interval: 30s # How often Flux checks for repository updates (new commits)
  ref:
    branch: main
  # To learn how to checkout private repositories, check
  # https://fluxcd.io/docs/components/source/gitrepositories/#spec-examples
  url: https://github.com/lollones/gitops-demo
  timeout: 30s
