apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-kustomization
  namespace: default
spec:
  interval: 30s
  path: ./demo
  prune: true
  serviceAccountName: automation-lorenzo
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: gitops-demo
